# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: mdillon/postgis:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432